const coroinhas = [
  { id: "1", nome: "Adrian", foto: "/imagens/Adrian-mestre.png" },
  { id: "2", nome: "Ana Luiza", foto: "/imagens/semfoto.jpg" },
  { id: "3", nome: "Áylla", foto: "/imagens/semfoto.jpg" },
  { id: "4", nome: "Aysha", foto: "/imagens/semfoto.jpg" },
  { id: "5", nome: "Beatriz Lemos", foto: "/imagens/beatriz-lemos.jpg" },
  { id: "6", nome: "Beatriz Martins", foto: "/imagens/beatriz_martins.jpeg" },
  { id: "7", nome: "Bianca", foto: "/imagens/bianca.jpeg" },
  { id: "8", nome: "Carla", foto: "/imagens/carla.png" },
  { id: "9", nome: "Carlos André", foto: "/imagens/carlos.png" },
  { id: "10", nome: "Cecília", foto: "/imagens/cecilia.png" },
  { id: "11", nome: "Charlys", foto: "/imagens/charlys.jpeg" },
  { id: "12", nome: "Clarice", foto: "/imagens/semfoto.jpg" },
  { id: "13", nome: "Clara Albuquerque", foto: "/imagens/semfoto.jpg" },
  { id: "14", nome: "Clara Martins", foto: "/imagens/claramartins.png" },
  { id: "15", nome: "Clara Santiago", foto: "/imagens/clara_santiago.jpeg" },
  { id: "16", nome: "Dafny", foto: "/imagens/dafny.png" },
  { id: "17", nome: "Davi", foto: "/imagens/semfoto.jpg" },
  { id: "18", nome: "Eduarda Cavalcante", foto: "/imagens/semfoto.jpg" },
  { id: "19", nome: "Fernando", foto: "/imagens/semfoto.jpg" },
  { id: "20", nome: "Francisco José", foto: "/imagens/semfoto.jpg" },
  { id: "21", nome: "Gabriel de Andrade", foto: "/imagens/joaogabriel.jpeg" },
  { id: "22", nome: "Gabriel Christian", foto: "/imagens/gabriel_christian.png" },
  { id: "23", nome: "Gabriel Gomes", foto: "/imagens/semfoto.jpg" },
  { id: "24", nome: "Gabrielle", foto: "/imagens/gabrielle.png" },
  { id: "25", nome: "Gustavo", foto: "/imagens/gustavo-mestre.png" },
  { id: "26", nome: "Isaías", foto: "/imagens/semfoto.jpg" },
  { id: "27", nome: "Isabelly Guedes", foto: "/imagens/semfoto.jpg" },
  { id: "28", nome: "Isadora Oliveira", foto: "/imagens/semfoto.jpg" },
  { id: "29", nome: "Isabelle", foto: "/imagens/semfoto.jpg" },
  { id: "30", nome: "João Pedro", foto: "/imagens/semfoto.jpg" },
  { id: "31", nome: "José Vitor", foto: "/imagens/semfoto.jpg" },
  { id: "32", nome: "Jhonnata", foto: "/imagens/semfoto.jpg" },
  { id: "33", nome: "Júlia", foto: "/imagens/semfoto.jpg" },
  { id: "34", nome: "Kacilane", foto: "/imagens/kacilane.png" },
  { id: "35", nome: "Kaciele", foto: "/imagens/kaciele.JPG" },
  { id: "36", nome: "Kauan", foto: "/imagens/semfoto.jpg" },
  { id: "37", nome: "Kaylane", foto: "/imagens/kaylane.png" },
  { id: "38", nome: "Larissa", foto: "/imagens/larissa.png" },
  { id: "39", nome: "Laura", foto: "/imagens/laura.png" },
  { id: "40", nome: "Marjory", foto: "/imagens/marjory.png" },
  { id: "41", nome: "Mariana", foto: "/imagens/mariana.png" },
  { id: "42", nome: "Marina", foto: "/imagens/semfoto.jpg" },
  { id: "43", nome: "Maria Luiza", foto: "/imagens/marialuiza.png" },
  { id: "44", nome: "Maria Lara", foto: "/imagens/semfoto.jpg" },
  { id: "45", nome: "Maria Rita", foto: "/imagens/semfoto.jpg" },
  { id: "46", nome: "Martha", foto: "/imagens/semfoto.jpg" },
  { id: "47", nome: "Melissa", foto: "/imagens/melissa.png" },
  { id: "48", nome: "Miguel Anselmo", foto: "/imagens/miguel_anselmo.jpeg" },
  { id: "49", nome: "Miguel Dourado", foto: "/imagens/semfoto.jpg" },
  { id: "50", nome: "Nalberto", foto: "/imagens/semfoto.jpg" },
  { id: "51", nome: "Pedro Guilherme", foto: "/imagens/semfoto.jpg" },
  { id: "52", nome: "Samyra", foto: "/imagens/semfoto.jpg" },
  { id: "53", nome: "Sophia", foto: "/imagens/sophia.jpeg" },
  { id: "54", nome: "Stefhany", foto: "/imagens/ste.png" },
  { id: "55", nome: "Taylania", foto: "/imagens/semfoto.jpg" },
  { id: "56", nome: "Thaissa", foto: "/imagens/thaissa.png" },
  { id: "57", nome: "Victor Martins", foto: "/imagens/victor_martins.png" },
  { id: "59", nome: "Victoria", foto: "/imagens/semfoto.jpg" }
];

export default coroinhas;