const coroinhas = [
  { id: "1", nome: "Adryan", foto: "/imagens/semfoto.jpg" },
  { id: "2", nome: "Ana Isabelly", foto: "/imagens/semfoto.jpg" },
  { id: "3", nome: "Ana Jéssica", foto: "/imagens/semfoto.jpg" },
  { id: "4", nome: "Ana Júlia", foto: "/imagens/julia-amorim.jpg" },
  { id: "5", nome: "Ana Karolyne", foto: "/imagens/semfoto.jpg" },
  { id: "6", nome: "Ana Kelly", foto: "/imagens/semfoto.jpg" },
  { id: "7", nome: "Ana Laura", foto: "/imagens/semfoto.jpg" },
  { id: "8", nome: "Ana Livia", foto: "/imagens/livia.jpeg" },
  { id: "9", nome: "Ana Victoria", foto: "/imagens/semfoto.jpg" },
  { id: "10", nome: "Ângelo", foto: "/imagens/semfoto.jpg" },
  { id: "11", nome: "Antônia Mariana", foto: "/imagens/semfoto.jpg" },
  { id: "12", nome: "Ashlee Silva", foto: "/imagens/semfoto.jpg" },
  { id: "13", nome: "Áylla", foto: "/imagens/semfoto.jpg" },
  { id: "14", nome: "Áysha", foto: "/imagens/semfoto.jpg" },
  { id: "15", nome: "Beatriz Lemos", foto: "/imagens/semfoto.jpg" },
  { id: "16", nome: "Beatriz Martins", foto: "/imagens/semfoto.jpg" },
  { id: "17", nome: "Bianca", foto: "/imagens/semfoto.jpg" },
  { id: "18", nome: "Brayan", foto: "/imagens/semfoto.jpg" },
  { id: "19", nome: "Carla", foto: "/imagens/semfoto.jpg" },
  { id: "20", nome: "Carlos André", foto: "/imagens/semfoto.jpg" },
  { id: "21", nome: "Cecilia", foto: "/imagens/semfoto.jpg" },
  { id: "22", nome: "Charlys", foto: "/imagens/charlys.jpeg" },
  { id: "23", nome: "Clara Albuquerque", foto: "/imagens/semfoto.jpg" },
  { id: "24", nome: "Clara Cavalcante", foto: "/imagens/clara-cavalcante.jpg" },
  { id: "25", nome: "Clara Freitas", foto: "/imagens/clara-freitas.jpg" },
  { id: "26", nome: "Clara Gondim", foto: "/imagens/semfoto.jpg" },
  { id: "27", nome: "Clara Martins", foto: "/imagens/claramartins.png" },
  { id: "28", nome: "Clara Santiago", foto: "/imagens/clara_santiago.jpeg" },
  { id: "29", nome: "Clarice", foto: "/imagens/semfoto.jpg" },
  { id: "30", nome: "Dafny", foto: "/imagens/dafny.png" },
  { id: "31", nome: "Danilo", foto: "/imagens/semfoto.jpg" },
  { id: "32", nome: "Davi Cardoso", foto: "/imagens/davi-cardoso.jpg" },
  { id: "33", nome: "Davi Sousa", foto: "/imagens/semfoto.jpg" },
  { id: "34", nome: "Eduarda Batista", foto: "/imagens/semfoto.jpg" },
  { id: "35", nome: "Eduarda Cavalcante", foto: "/imagens/semfoto.jpg" },
  { id: "36", nome: "Eduarda Cordeiro", foto: "/imagens/semfoto.jpg" },
  { id: "37", nome: "Fernando", foto: "/imagens/fernando.jpg" },
  { id: "38", nome: "Francisco Adryan", foto: "/imagens/semfoto.jpg" },
  { id: "39", nome: "Francisco José", foto: "/imagens/semfoto.jpg" },
  { id: "40", nome: "Gabriel Cristian", foto: "/imagens/semfoto.jpg" },
  { id: "41", nome: "Gabriel Gomes", foto: "/imagens/semfoto.jpg" },
  { id: "42", nome: "Gabriella Lima", foto: "/imagens/semfoto.jpg" },
  { id: "43", nome: "Gabrielle", foto: "/imagens/semfoto.jpg" },
  { id: "44", nome: "Gustavo", foto: "/imagens/semfoto.jpg" },
  { id: "45", nome: "Hellen", foto: "/imagens/semfoto.jpg" },
  { id: "46", nome: "Isabelle", foto: "/imagens/semfoto.jpg" },
  { id: "47", nome: "Isabelly Guedes", foto: "/imagens/semfoto.jpg" },
  { id: "48", nome: "Isadora", foto: "/imagens/semfoto.jpg" },
  { id: "49", nome: "Isaias", foto: "/imagens/semfoto.jpg" },
  { id: "50", nome: "Ivina", foto: "/imagens/semfoto.jpg" },
  { id: "51", nome: "Izabelle", foto: "/imagens/izabelle.jpg" },
  { id: "52", nome: "Jhonnata", foto: "/imagens/semfoto.jpg" },
  { id: "53", nome: "João Carlos", foto: "/imagens/semfoto.jpg" },
  { id: "54", nome: "João Gabriel", foto: "/imagens/semfoto.jpg" },
  { id: "55", nome: "João Pedro", foto: "/imagens/semfoto.jpg" },
  { id: "56", nome: "João Rafael", foto: "/imagens/semfoto.jpg" },
  { id: "57", nome: "João Victor", foto: "/imagens/semfoto.jpg" },
  { id: "58", nome: "José Vitor", foto: "/imagens/semfoto.jpg" },
  { id: "59", nome: "Joyce", foto: "/imagens/semfoto.jpg" },
  { id: "60", nome: "Júlia Martins", foto: "/imagens/semfoto.jpg" },
  { id: "61", nome: "Juliana", foto: "/imagens/semfoto.jpg" },
  { id: "62", nome: "Kaciele", foto: "/imagens/semfoto.jpg" },
  { id: "63", nome: "Kacilane", foto: "/imagens/semfoto.jpg" },
  { id: "64", nome: "Karla Sophya", foto: "/imagens/semfoto.jpg" },
  { id: "65", nome: "Kauan", foto: "/imagens/semfoto.jpg" },
  { id: "66", nome: "Kauane", foto: "/imagens/semfoto.jpg" },
  { id: "67", nome: "Kayllane", foto: "/imagens/semfoto.jpg" },
  { id: "68", nome: "Larissa", foto: "/imagens/semfoto.jpg" },
  { id: "69", nome: "Lorem", foto: "/imagens/semfoto.jpg" },
  { id: "70", nome: "Luiz Davi", foto: "/imagens/luiz-davi.jpeg" },
  { id: "71", nome: "Luiza Alves", foto: "/imagens/semfoto.jpg" },
  { id: "72", nome: "Luíza Souza", foto: "/imagens/luiza-souza.jpg" },
  { id: "73", nome: "Marcos Manuel", foto: "/imagens/marcos-manuel.jpg" },
  { id: "74", nome: "Maria Júlia", foto: "/imagens/semfoto.jpg" },
  { id: "75", nome: "Maria Lara", foto: "/imagens/semfoto.jpg" },
  { id: "76", nome: "Maria Laura", foto: "/imagens/semfoto.jpg" },
  { id: "77", nome: "Maria Luíza", foto: "/imagens/semfoto.jpg" },
  { id: "78", nome: "Maria Rita", foto: "/imagens/semfoto.jpg" },
  { id: "79", nome: "Maria Sophia", foto: "/imagens/semfoto.jpg" },
  { id: "80", nome: "Mariana Travassos", foto: "/imagens/semfoto.jpg" },
  { id: "81", nome: "Marina", foto: "/imagens/semfoto.jpg" },
  { id: "82", nome: "Marjorye", foto: "/imagens/semfoto.jpg" },
  { id: "83", nome: "Martha", foto: "/imagens/semfoto.jpg" },
  { id: "84", nome: "Marya da Costa", foto: "/imagens/marya-da-costa.jpg" },
  { id: "85", nome: "Mayra Marilha", foto: "/imagens/mayra.jpg" },
  { id: "86", nome: "Melissa", foto: "/imagens/melissa.png" },
  { id: "87", nome: "Miguel Anselmo", foto: "/imagens/miguel_anselmo.jpeg" },
  { id: "88", nome: "Miguel Dourado", foto: "/imagens/semfoto.jpg" },
  { id: "89", nome: "Mirela", foto: "/imagens/mirela.jpg" },
  { id: "90", nome: "Nalberto", foto: "/imagens/semfoto.jpg" },
  { id: "91", nome: "Paulo Henrique", foto: "/imagens/semfoto.jpg" },
  { id: "92", nome: "Pedro Fernandes", foto: "/imagens/semfoto.jpg" },
  { id: "93", nome: "Pedro Guilherme", foto: "/imagens/semfoto.jpg" },
  { id: "94", nome: "Pedro Santiago", foto: "/imagens/semfoto.jpg" },
  { id: "95", nome: "Rafael Silva", foto: "/imagens/rafael-rodrigues.jpg" },
  { id: "96", nome: "Samyra", foto: "/imagens/semfoto.jpg" },
  { id: "97", nome: "Sophia", foto: "/imagens/semfoto.jpg" },
  { id: "98", nome: "Stefhany", foto: "/imagens/semfoto.jpg" },
  { id: "99", nome: "Taylânia", foto: "/imagens/semfoto.jpg" },
  { id: "100", nome: "Thaissa", foto: "/imagens/semfoto.jpg" },
  { id: "101", nome: "Theo", foto: "/imagens/theo.jpg" },
  { id: "102", nome: "Thiago", foto: "/imagens/thiago.jpg" },
  { id: "103", nome: "Vívian", foto: "/imagens/semfoto.jpg" },
  { id: "104", nome: "Wesley", foto: "/imagens/semfoto.jpg" },
  { id: "105", nome: "Yasmin", foto: "/imagens/yasmin.jpg" }
];

export default coroinhas;