const coroinhas = [
  { id: "1", nome: "Adrian", foto: "/imagens/Adrian-mestre.png" },
  { 
    id: "2", 
    nome: "Ana Luiza", 
    foto: "/imagens/semfoto.jpg",
    permissoes: [
      "Centro Pastoral-18h30-Sexta",
      "Guabiraba-19h-Quarta",
      "Matriz-07h-Domingo","Matriz-09h-Domingo","Matriz-19h-Domingo",
      "Matriz-19h-Quarta",
      "Matriz-19h-Sábado",
      "Rosário-19h-Sexta",
    ]
   },
  { 
    id: "3", 
    nome: "Áylla", 
    foto: "/imagens/semfoto.jpg",
    permissoes: [
      "Centro Pastoral-17h-Domingo",
      "Matriz-07h-Domingo","Matriz-09h-Domingo","Matriz-19h-Domingo",
    ]
   },
  { 
    id: "4", 
    nome: "Aysha", 
    foto: "/imagens/semfoto.jpg",
    permissoes: [
      "Centro Pastoral-17h-Domingo",
      "Matriz-07h-Domingo","Matriz-09h-Domingo","Matriz-19h-Domingo",
    ]
   },
  { 
    id: "5", 
    nome: "Beatriz Lemos", 
    foto: "/imagens/beatriz-lemos.jpg",
    permissoes: [
      "Centro Pastoral-18h30-Sexta",
      "Centro Pastoral-17h-Domingo",
      "Divino-07h-Domingo","Divino-17h-Domingo",
      "Mãe Rainha-19h-Quinta",
      "Matriz-07h-Domingo","Matriz-09h-Domingo","Matriz-19h-Domingo",
      "Matriz-19h-Segunda",
      "Matriz-19h-Terça",
      "Matriz-19h-Quarta",
      "Matriz-19h-Quinta",
      "Matriz-19h-Sexta",
      "Matriz-19h-Sábado",
      "Outra Banda-19h-Sábado",
      "Santa Luzia-17h-Sábado","Santa Luzia-19h-Sábado",
      "Rosário-19h-Sexta",
    ]
   },
  { 
    id: "6", 
    nome: "Beatriz Martins", 
    foto: "/imagens/beatriz.jpeg",
    permissoes: [
      "Centro Pastoral-17h-Domingo",
      "Matriz-07h-Domingo","Matriz-09h-Domingo","Matriz-19h-Domingo",
      "Matriz-19h-Terça",
      "Matriz-19h-Quinta",
      "Matriz-19h-Sábado",
    ]
   },
  { 
    id: "7", 
    nome: "Carla", 
    foto: "/imagens/carla.png",
    permissoes: [
      "Matriz-09h-Domingo",
    ]
   },
  { 
    id: "8", 
    nome: "Carlos André", 
    foto: "/imagens/carlos.png",
    permissoes: [
      "Centro Pastoral-18h30-Sexta",
      "Centro Pastoral-17h-Domingo",
      "Matriz-19h-Domingo",
      "Matriz-12h-Segunda",
      "Matriz-12h-Terça",
      "Matriz-12h-Quarta",
      "Matriz-19h-Quarta",
      "Matriz-12h-Quinta",
      "Matriz-12h-Sexta",
      "Matriz-19h-Sábado",
      "Novo Parque Iracema-19h-Domingo",
      "Rosário-19h-Sexta",
    ]
   },
  { id: "9", nome: "Cecília", foto: "/imagens/cecilia.png" },
  { id: "10", nome: "Charlys", foto: "/imagens/semfoto.jpg" },
  { id: "11", nome: "Clarisse", foto: "/imagens/semfoto.jpg" },
  { 
    id: "12", 
    nome: "Clara Albuquerque", 
    foto: "/imagens/semfoto.jpg",
    permissoes: [
      "Centro Pastoral-18h30-Sexta",
      "Centro Pastoral-17h-Domingo",
      "Divino-07h-Domingo","Divino-17h-Domingo",
      "Mãe Rainha-19h-Quinta",
      "Matriz-07h-Domingo","Matriz-09h-Domingo","Matriz-19h-Domingo",
      "Matriz-19h-Segunda",
      "Matriz-19h-Terça",
      "Matriz-19h-Quarta",
      "Matriz-19h-Quinta",
      "Matriz-19h-Sexta",
      "Matriz-19h-Sábado",
      "Santa Luzia-17h-Sábado","Santa Luzia-19h-Sábado"
    ]
   },
  { 
    id: "13", 
    nome: "Clara Martins",
    foto: "/imagens/claramartins.png",
    permissoes: [
      "Centro Pastoral-18h30-Sexta",
      "Centro Pastoral-17h-Domingo",
      "Divino-07h-Domingo","Divino-17h-Domingo",
      "Matriz-07h-Domingo","Matriz-09h-Domingo","Matriz-19h-Domingo",
      "Matriz-19h-Segunda",
      "Matriz-19h-Terça",
      "Matriz-19h-Quarta",
      "Matriz-19h-Quinta",
      "Matriz-19h-Sexta",
      "Matriz-19h-Sábado",
      "Outra Banda-19h-Sábado",
      "Parque das Rosas-19h-Quinta",
      "São José-09h-Domingo",
      "Santa Luzia-17h-Sábado","Santa Luzia-19h-Sábado",
      "Rosário-19h-Sexta",
    ]
   },
  { id: "14", nome: "Clara Santiago", foto: "/imagens/semfoto.jpg" },
  { id: "15", nome: "Dafny", foto: "/imagens/dafny.png" },
  { id: "16", nome: "Davi", foto: "/imagens/semfoto.jpg" },
  { id: "17", nome: "Eduarda Cavalcante", foto: "/imagens/semfoto.jpg" },
  { id: "18", nome: "Fernando", foto: "/imagens/semfoto.jpg" },
  { id: "19", nome: "Francisco José", foto: "/imagens/semfoto.jpg" },
  { id: "20", nome: "Gabriel Andrade", foto: "/imagens/joaogabriel.jpeg" },
  { id: "21", nome: "Gabriel Christian", foto: "/imagens/semfoto.jpg" },
  { id: "22", nome: "Gabriel Gomes", foto: "/imagens/semfoto.jpg" },
  { id: "23", nome: "Gabriele", foto: "/imagens/semfoto.jpg" },
  { id: "24", nome: "Gustavo", foto: "/imagens/gustavo-mestre.png" },
  { id: "25", nome: "Isaías", foto: "/imagens/semfoto.jpg" },
  { id: "26", nome: "Ingrid", foto: "/imagens/semfoto.jpg" },
  { id: "27", nome: "Izadora", foto: "/imagens/semfoto.jpg" },
  { id: "28", nome: "Isabelly Guedes", foto: "/imagens/semfoto.jpg" },
  { id: "29", nome: "Isadora Oliveira", foto: "/imagens/semfoto.jpg" },
  { 
    id: "30", 
    nome: "Isabelle", 
    foto: "/imagens/semfoto.jpg",
    permissoes: [
      "Centro Pastoral-18h30-Sexta",
      "Centro Pastoral-17h-Domingo",
      "Divino-07h-Domingo","Divino-17h-Domingo",
      "Matriz-07h-Domingo","Matriz-09h-Domingo","Matriz-19h-Domingo",
      "Matriz-19h-Sábado",
      "São José-09h-Domingo",
      "Santa Luzia-17h-Sábado","Santa Luzia-19h-Sábado",
      "Rosário-19h-Sexta",
    ]
   },
  { id: "31", nome: "Jéssica", foto: "/imagens/jessica.png" },
  { id: "32", nome: "João Pedro", foto: "/imagens/semfoto.jpg" },
  { id: "33", nome: "José Vitor", foto: "/imagens/semfoto.jpg" },
  { id: "34", nome: "Jhonnata", foto: "/imagens/semfoto.jpg" },
  { id: "35", nome: "Julia", foto: "/imagens/semfoto.jpg" },
  { id: "36", nome: "Kacilane", foto: "/imagens/kacilane.png" },
  { id: "37", nome: "Kaciele", foto: "/imagens/kaciele.JPG" },
  { id: "38", nome: "Kauan ", foto: "/imagens/semfoto.jpg"}, 
  { id: "39", nome: "Kaylane", foto: "/imagens/semfoto.jpg" },
  { id: "40", nome: "Larissa", foto: "/imagens/semfoto.jpg" },
  { id: "41", nome: "Laura", foto: "/imagens/laura.png" },
  { 
    id: "42", 
    nome: "Letícia", 
    foto: "/imagens/semfoto.jpg",
    permissoes: [
      "Coité-17h-Sábado", "Coité-19h-Sábado", 
      "Coité-17h-Domingo", "Coité-19h-Domingo",
      "Parque São João-17h-Sábado", "Parque São João-19h-Sábado",
      "Parque São João-17h-Domingo", "Parque São João-19h-Domingo",
    ] 
  },
  { id: "43", 
    nome: "Liah", 
    foto: "/imagens/liah.jpg",
    permissoes: [
      "Centro Pastoral-17h-Domingo",
      "Divino-07h-Domingo","Divino-17h-Domingo",
      "Matriz-07h-Domingo",
    ]  
   },
  { id: "44", nome: "Luiz Felipe", foto: "/imagens/luizfelipe.jpeg" },
  { id: "45", nome: "Luiz Guilherme", foto: "/imagens/semfoto.jpg" },
  { id: "46", nome: "Marjory", foto: "/imagens/marjory.png" },
  { id: "47", nome: "Mariana", foto: "/imagens/semfoto.jpg" },
  { id: "48", nome: "Marina", foto: "/imagens/semfoto.jpg" },
  { 
    id: "49", 
    nome: "Maria Luiza", 
    foto: "/imagens/marialuiza.png",
    permissoes: [
      "Centro Pastoral-18h30-Sexta",
      "Centro Pastoral-17h-Domingo",
      "Guabiraba-19h-Quarta",
      "Matriz-07h-Domingo", "Matriz-09h-Domingo","Matriz-19h-Domingo",
      "Matriz-19h-Segunda",
      "Matriz-19h-Terça",
      "Matriz-19h-Quarta",
      "Matriz-19h-Quinta",
      "Matriz-19h-Sexta",
      "Matriz-19h-Sábado",
      "Rosário-19h-Sexta",
    ]
   },
  { id: "50", nome: "Maria Lara", foto: "/imagens/semfoto.jpg" },
  { id: "51", nome: "Maria Rita", foto: "/imagens/semfoto.jpg" },
  { id: "52", nome: "Martha", foto: "/imagens/semfoto.jpg" },
  { id: "53", nome: "Melissa", foto: "/imagens/semfoto.jpg" },
  { id: "54", nome: "Miguel Anselmo", foto: "/imagens/miguelanselmo.png" },
  { id: "55", nome: "Miguel Dourado", foto: "/imagens/semfoto.jpg" },
  { id: "56", nome: "Nalberto", foto: "/imagens/semfoto.jpg" },
  { id: "57", nome: "Pedro Guilherme", foto: "/imagens/semfoto.jpg" },
  {
    id: "58",
    nome: "Ramon",
    foto: "/imagens/ramon.png",
    permissoes: [
      "Centro Pastoral-17h-Domingo",
      "Centro Pastoral-18h30-Sexta",
      "Coité-17h-Sábado","Coité-19h-Sábado",
      "Coité-17h-Domingo","Coité-19h-Domingo",
      "Matriz-07h-Domingo","Matriz-19h-Domingo",
      "Matriz-19h-Segunda",
      "Matriz-19h-Terça",
      "Matriz-19h-Quinta",
      "Matriz-19h-Sexta",
      "Matriz-19h-Sábado",
      "Parque São João-17h-Sábado", "Parque São João-19h-Sábado",
      "Parque São João-17h-Domingo", "Parque São João-19h-Domingo",
    ]
  },
  { id: "59", nome: "Rayssa", foto: "/imagens/rayssa.png" },
  { id: "60", nome: "Samira", foto: "/imagens/semfoto.jpg" },
  { id: "61", nome: "Sophia", foto: "/imagens/semfoto.jpg" },
  { id: "62", nome: "Stefhany", foto: "/imagens/ste.png" },
  { id: "63", nome: "Taylania", foto: "/imagens/semfoto.jpg" },
  { id: "64", nome: "Thaissa", foto: "/imagens/thaissa.png" },
  { 
    id: "65", 
    nome: "Victor Martins", 
    foto: "/imagens/semfoto.jpg",
    permissoes: [
      "Urucará-17h-Sábado","Urucará-19h-Sábado",
      "Matriz-09h-Domingo",
    ]
  },
  {
    id: "66",
    nome: "Victor Manuel",
    foto: "/imagens/Victor.jfif",
    permissoes: [
      "Matriz-07h-Domingo", 
      "Centro Pastoral-17h-Domingo", 
      "Matriz-19h-Domingo",
    ]
  },
  { id: "67", nome: "Victoria", foto: "/imagens/semfoto.jpg" },
  { id: "68", nome: "Yasmim", foto: "/imagens/semfoto.jpg" }
];

export default coroinhas;
